FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY dist ./dist
COPY prisma ./prisma
COPY prisma.config.ts ./prisma.config.ts
COPY src/generated ./src/generated

EXPOSE 3000
CMD ["node", "dist/src/main"]
