ALTER TABLE "AdSpend" ALTER COLUMN "spend" TYPE DECIMAL(18,4);
ALTER TABLE "AdSpend" ADD COLUMN "vatBasis" TEXT NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE "AdSpend" ALTER COLUMN "impressions" DROP NOT NULL;
